[toolchain]
anchor_version = "0.26.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
goticker = "9AcKM9kiHLxM22V3QUY6QsxQFysWiE8oLqAUA6PrQRWB"
ticker-economy = "6qNwVB7W2Mgb2AMB74cxKz9u5q3nf3dyPndHNN2y3Hna"

[programs.mainnet]
goticker = "9AcKM9kiHLxM22V3QUY6QsxQFysWiE8oLqAUA6PrQRWB"
ticker-economy = "6qNwVB7W2Mgb2AMB74cxKz9u5q3nf3dyPndHNN2y3Hna"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "4YEVrTraKvHmQLbLnqNhCj3W843Rn8tABV4kHNhPpyqr"
program = "11111111111111111111111111111112" 