name: Build Solana Programs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache Solana CLI
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/solana
          ~/.local/bin/solana*
        key: ${{ runner.os }}-solana-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-solana-
          
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        
    - name: Install Solana CLI
      run: |
        # Download pre-built binary directly
        mkdir -p $HOME/.local/bin
        cd $HOME/.local/bin
        # Try to download from GitHub releases
        wget -q https://github.com/solana-labs/solana/releases/download/v1.18.26/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -O solana.tar.bz2 || \
        wget -q https://github.com/solana-labs/solana/releases/download/v1.18.25/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -O solana.tar.bz2 || \
        wget -q https://github.com/solana-labs/solana/releases/download/v1.18.24/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -O solana.tar.bz2
        tar -xjf solana.tar.bz2
        mv solana-release/bin/* .
        rm -rf solana-release solana.tar.bz2
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        export PATH="$HOME/.local/bin:$PATH"
        # Verify installation
        ls -la $HOME/.local/bin/
        $HOME/.local/bin/solana --version
        
    - name: Install Anchor CLI
      run: |
        npm install -g @coral-xyz/anchor-cli@0.26.0
        
    - name: Verify installations
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        echo "Verifying all installations..."
        $HOME/.local/bin/solana --version
        anchor --version
        rustc --version
        cargo --version
        
    - name: Configure Solana for devnet
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        $HOME/.local/bin/solana config set --url https://api.devnet.solana.com
        
    - name: Build programs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        anchor build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solana-programs
        path: |
          target/deploy/*.so
          target/idl/*.json
        retention-days: 7
        
    - name: List built programs
      run: |
        echo "Built programs:"
        ls -la target/deploy/ || echo "No deploy directory found"
        echo "IDL files:"
        ls -la target/idl/ || echo "No IDL directory found" 